### ISSUE TITLE
On Enter Key click focus gets lost

### ISSUE THREAD

**Issue by KavyaShetty** [obogo/angular-focusmanager#10]
Hi, When we click on enter key the focus gets lost.
Can we retain it at the current element?

**Comment by KavyaShetty** [comment]
Any update on this?

**Comment by roboncode** [comment]
Thank you for your submission. It will be added to the backlog and reviewed.

**Comment by roboncode** [comment]
I am not finding any issues relating to this. If you provide an example I can look into it further. All test I have performed the focus does not get lost using the ENTER key.
