### ISSUE TITLE
Autofocus with ng-repeat

### ISSUE THREAD

**Issue by KavyaShetty** [obogo/angular-focusmanager#11]
How can I set autofocus to first element of ng-repeat?
Earlier, with focus-element it used to work with the following syntax:-
```javascript
focus-element="{autofocus : {{rowIndex}} == {{rowIndex + $index}}}
```
Currently with focus-autofocus I'm trying the following but it doesn't work:-
```javascript
{{$first?focus-autofocus:''}}
```
Is there something else that can be done?

**Comment by KavyaShetty** [comment]
Any updates on this?

**Comment by roboncode** [comment]
Thank you for this example. It will be added to the backlog and reviewed.

**Comment by roboncode** [comment]
You can select what item to select by either 

    focus-autofocus="{{$first?0:1}}"

Or...

    focus-autofocus="{{$index === 0?0:1}}"

The second example would let you select any index where the first example if specific.
