### ISSUE TITLE
In case of popup focus shifts to background page also on tab

### ISSUE THREAD

**Issue by KavyaShetty** [obogo/angular-focusmanager#12]
Hi, With focus-autofocus implementation I'm able to get focus to elements that are in parent page when popups are open.
That is the elements that are not on the popup but in the background.
I have used focus-group="" focus-stack="" focus-group-head="loop" focus-group-tail="loop" for the popups.
Is there something else that can be done?

**Comment by roboncode** [comment]
If you would provide an example, i would be happy to review it. There is an example in the focus manager under "focus stack" that demonstrates how to setup a loop for a popup. http://obogo.github.io/angular-focusmanager/
