### ISSUE TITLE
pressing enter while focused in form input does not submit form

### ISSUE THREAD

**Issue by ilovett** [obogo/angular-focusmanager#13]
I see that when enter is pressed it is replaced with a mouse click.  Because of this, when I am focused in an input inside a form and press enter, the form does not get submitted as expected.  I was able to get form submission back by commenting out event prevent default / stop propagation in the following block:

```
            if (activeElement.type === "text" || activeElement.type === "textarea" || activeElement.getAttribute("contentEditable") === "true") {
                return;
            }
//            evt.preventDefault();
//            evt.stopPropagation();
            fireEvent(activeElement, "mousedown");
            fireEvent(activeElement, "mouseup");
            fireEvent(activeElement, "click");
```
Furthermore, the input types I was trying this with were `input [type=number]` and `input [type=password]`.  If you can give me some pointers to as to why you are replacing enter with clicks, I'd be happy to contribute... something like this:

```
if (['text', 'textarea', 'password', 'number', 'date'].indexOf(activeElement.type) > -1 || activeElement.getAttribute('contentEditable') ==== 'true)
```

Can you explain why you wouldn't do it on ANY `input` element?

Here's a list of all the input types to consider:
http://www.w3schools.com/html/html_form_input_types.asp

**Comment by roboncode** [comment]
Thanks for submitting this issue. Yes those should be included as part of the text input items. If I remember correctly, the reason the ENTER key simulates these events is to allow items such as radios and checkboxes to respond to the ENTER key which is common for accessibility. By default the browser allows the users toggle using the SPACEBAR, this just allows them to use the ENTER key as well.

**Comment by ilovett** [comment]
Awesome, thanks.  I wasn't sure if I should bump the version or leave that to you.

**Comment by roboncode** [comment]
Bumping right now. Also adding you onto the list of contributors.
