### ISSUE TITLE
Focus an element by name

### ISSUE THREAD

**Issue by tolemac** [obogo/angular-focusmanager#15]
Hi, 

In some situations I need to focus an input, have you something like?:

    <input ng-model="username" focus-name="userInput"/>
    <button ng-click="fm.setFocus('userInput');

Thanks in advance.

**Comment by roboncode** [comment]
You can achieve this by doing the following with the existing API:

    var el = document.querySelector('[focus-name="userInput"]');
    fm.manager.focus(el);

**Comment by tolemac** [comment]
True, true. I will use it.

Many times in SPA's I have to reset the focus to the first element, or focus a specific element. I think to have the posibility of to set focus to specific element would be good.
At the moment I think to extend the manager with focusByName function, something like:

    fm.manager.focusByName = function (name) {
        var el = document.querySelector('[focus-name="userInput"]');
        if (el)
            fm.manager.focus(el);
    }

Perhaps in the future the manager support it natively ;)
