### ISSUE TITLE
How to ignore control?

### ISSUE THREAD

**Issue by tolemac** [obogo/angular-focusmanager#16]
I would like to ignore a little button in my focus-group, I don't want that this control got focus, exists something like `focus-ignore` to skip this control in the focus flow?

Thanks,

**Comment by roboncode** [comment]
I will have a solution for this in the next release.

**Comment by roboncode** [comment]
Release 0.3.9, you can add a class "focus-ignore" to an element and the FM will skip it as long as that class is present on that element.
