### ISSUE TITLE
Highlight shouldnt focuss elements outside focus-group

### ISSUE THREAD

**Issue by edriang** [obogo/angular-focusmanager#19]
I'm having trouble with highlight directive, because it is showing on elements outside my form, like nav buttons, for example.

I'had to patch the library to avoid this. Currently I'm checking if the focused element is inside the highlight form parent, but maybe a simple "target" attribute on the highlight directive could be better aproach

**Comment by roboncode** [comment]
I would recommend if you would like this functionality to clone the highlighter directive and create a custom solution. Since the highlighter directive acts independently from FM directives this would be easy to do. The highlighter that is part of FM is working as intended.
