### ISSUE TITLE
Kendo drop downList focus issue

### ISSUE THREAD

**Issue by saeidehmsm** [obogo/angular-focusmanager#20]
I 'm using focus manager for ordering the tab-index. it works well for all elements except for kendo drop down. Kendo drop down dynamically add a span that wrap dropdown.So, fm-id and fm-parent should be added to span.I think focus manager add fm-id and fm-parent for static elements on a page,while it should be added dynamically too.

**Comment by roboncode** [comment]
Please provide a description and if possible an example.

**Comment by saeidehmsm** [comment]
Hi Rob,
My problem is fixed. I added fm-id and fm-parent to span after kendo drop down widget created.

 $rootScope.$on("kendoWidgetCreated", function (event, widget) {
        if (widget.options.name == "DropDownList") {
            setTimeout(function () {
                if ($(widget.element[0]).attr("fm-id") && $(widget.element[0]).attr("fm-parent")) {
                    $(widget.element[0].closest(".k-dropdown")).attr("fm-id", $(widget.element[0]).attr('fm-id'));
                    $(widget.element[0].closest(".k-dropdown")).attr("fm-parent", $(widget.element[0]).attr('fm-parent'));
                    $(widget.element[0]).removeAttr("fm-id");
                    $(widget.element[0]).removeAttr("fm-parent");
                }
            }, 0);
        }
    });

**Comment by saeidehmsm** [comment]
Hi Rob,
My problem is fixed. I added fm-id and fm-parent to span after kendo drop down widget created.
 $rootScope.$on("kendoWidgetCreated", function (event, widget) {        if (widget.options.name == "DropDownList") {            setTimeout(function () {                if ($(widget.element[0]).attr("fm-id") && $(widget.element[0]).attr("fm-parent")) {                    $(widget.element[0].closest(".k-dropdown")).attr("fm-id", $(widget.element[0]).attr('fm-id'));                    $(widget.element[0].closest(".k-dropdown")).attr("fm-parent", $(widget.element[0]).attr('fm-parent'));                    $(widget.element[0]).removeAttr("fm-id");                    $(widget.element[0]).removeAttr("fm-parent");                }            }, 0);        }    });

    On Thursday, January 28, 2016 8:08 PM, Rob Taylor <notifications@github.com> wrote:
 

 Please provide a description and if possible an example.—

**Comment by roboncode** [comment]
Glad to hear! Thanks for leaving the example also.
