### ISSUE TITLE
support for Skip TabStop (condition based)

### ISSUE THREAD

**Issue by shashykant** [obogo/angular-focusmanager#21]
Is there a feature to support Skipping of tab stop?

lets say i have following controls A, B, C, D E.

I can navigate from A to E pressing Tabs. What If I want to Skip D or any other element.
hence navigations works as A-B-C-E. 
press tab at D must reach E & Shift-Tab must reach B.

**Comment by roboncode** [comment]
You can do this by adding the class "focus-ignore" onto an element.
