### ISSUE TITLE
Angular 2 version

### ISSUE THREAD

**Issue by tolemac** [obogo/angular-focusmanager#23]
Do you plan to port it to Angular 2 ?

**Comment by tolemac** [comment]
Yup!

I have ported this to Angular 2, I have working a version with `focus-group` and `focus-autofocus` directives.

I go out by holydays today I'll back in two weeks, when I go back I'll try to upload it to github.

**Comment by roboncode** [comment]
Yes I will have an Angular 2 version shortly.

**Comment by tolemac** [comment]
Wow, it will be great! I'll wait for it. 

Thanks!

**Comment by tolemac** [comment]
I have implemented my own library inspired on this project.

https://github.com/tolemac/tolefocus

Is framework agnostic and I'm using that actually in angular2 projects and works fine by the moment.
