### ISSUE TITLE
Setting up focus back to calling button element is not working in case of Modal dialog

### ISSUE THREAD

**Issue by yogeshp** [obogo/angular-focusmanager#5]
Hi, 
Its really a good javascript :) i don't need to care about setting up focus and tab index for html element manually.

In my application i am using bootstrap modal dialog box. When html page loads it sets focus on default button. When i hit "enter" key it opens dialog box and again default button get selected on  modal dialog. When i hit "enter" key again on modal dialog button it closes the modal dialog however focus not returning to calling button which actually works in your demo application. I have observed the same behaviour in <b>angular strap</b> as well.

I have created sample on plunker
http://embed.plnkr.co/jwNjrXCjMRLk5Jg79nTw/preview

am i missing something ?

-Thanks,
Yogesh

**Comment by roboncode** [comment]
Thanks for this example. I am looking into this. I also notice there is an error being produced. Rob

**Comment by roboncode** [comment]
The errors should be gone in the focus manager with the latest release, however to support dialogs you should use ng-if, so the dialog is created and destroyed. See the example "Using focus-stack" in the example page, http://obogo.github.io/angular-focusmanager/. It uses bootstrap and shows you how to use the focus-autofocus, focus-group, and focus-stack combined.
