### ISSUE TITLE
bower ENOTFOUND     Package angular-focusmanager not found

### ISSUE THREAD

**Issue by brunomacromind** [obogo/angular-focusmanager#6]
bower ENOTFOUND     Package angular-focusmanager not found

**Comment by swestner** [comment]
+1

**Comment by roboncode** [comment]
Perhaps I am doing something differently. I did "bower install angular-focusmanager" and it worked. Could you please provide steps to reproduce? Thanks.

**Comment by frexos** [comment]
Hi all, I had the same problem and after viewing the comments I noticed the following:
The instructions on Github note "bower install angular-focus-manager". Specifically there is one '-' more than the instructions from  roboncode. 

In other words  "bower install angular-focusmanager" while "bower install angular-focus-manager" doesnt

**Comment by roboncode** [comment]
I updated the readme file. Thanks. Rob
