### ISSUE TITLE
Setting auto focus on different elements not working in case of show hide div

### ISSUE THREAD

**Issue by KavyaShetty** [obogo/angular-focusmanager#7]
Hi, 
I'm trying to set auto-focus on 2 different elements in same page based on the visibility of parent div. 
I have 2 divs with some elements in them, if the 1st div is visible the auto-focus should be set on element with lowest focus-index in the 1st div.
And if the 1st div is hidden the auto-focus should be set on element with lowest focus-index in the 2nd div.
I have tried applying auto-focus on both the elements but this doesn't seem to work.
Am I missing something?

I have also created a sample for reference 
http://plnkr.co/edit/cjOV9lftnMghOzvg6iJ0?p=preview

**Comment by roboncode** [comment]
Thanks for the example. I made a fix and bumped the version to 0.3.0. I changed focus-element to focus-autofocus. It supports handling priority. I have updated example on this site and the plunker example here http://plnkr.co/edit/75ZpY9o79KytZbPgdqmR?p=preview

**Comment by KavyaShetty** [comment]
This works. Thanks.
