### ISSUE TITLE
Setting auto focus not working in case of expand collapse div

### ISSUE THREAD

**Issue by KavyaShetty** [obogo/angular-focusmanager#8]
Hi,
I have expand collapse div on my page. On expand click, collapse button is shown and auto-focus should be set on the element with lowest focus index in the expanded div.
And on collapse button click, the div should hide and auto-focus should now be on visible expand button.
I have tried applying focus-autofocus to the elements but this doesn't seem to work.
Is there something else that can be done?

Following is a sample for reference 
http://plnkr.co/edit/vQ7NDoxBnIsximxFZmT7?p=preview

**Comment by KavyaShetty** [comment]
Any update on this issue?

**Comment by KavyaShetty** [comment]
Is there any workaround for this issue?

**Comment by roboncode** [comment]
The autofocus feature only works when the item comes into view the first time. You should try using ng-if if you want it to repeat. The autofocus will not return back to the first box when the second one disappears. With the example. I don't really quite get what you are trying to achieve having looked at it.

**Comment by KavyaShetty** [comment]
In the example, I'm trying to return back to the first box when the second one disappears. That means when I click on 'Hide Div' button the div gets hidden and 'Show Div' button comes into picture I want this element to be now focused. Is there some way to achieve this.

I have modified the plunk with ng-if for reference.
http://plnkr.co/edit/dmvk7si4SxF5AjRCTzHm?p=preview

**Comment by KavyaShetty** [comment]
Is there any way to get the above working?

**Comment by KavyaShetty** [comment]
Can we something on similar lines with popups - "focus-stack" for show hide div?

**Comment by KavyaShetty** [comment]
Any update on this?

**Comment by roboncode** [comment]
There isn't anything in the focus manager that will automatically support this feature, You could listen for a $destroy on the ng-if and then inject the "focusManager" service and call focusManager.focus(el) when that element is destroyed back on the desired element.

**Comment by KavyaShetty** [comment]
I have tried listening to the $destroy on the ng-if and then calling focusManager.focus(el) but still no success. 

I'm doing something like follows:-

```javascript
 module.directive("ngIf", ["focusManager", "focusQuery", function (focusManager, focusQuery) {
  var showHideElement=null;
        return {
            link: function (scope, element, attrs) {
                showHideElement = focusQuery.getElementId(focusManager.activeElement);
                scope.$on("$destroy", function () {
                    if (showHideElement!=null) {
                       var el = focusQuery.getElement(showHideElement);
                        if (el) {
                            focusManager.focus(el);
                        }
                    }
                });
            }
        };
 }]);
```
Is there something missing?

**Comment by KavyaShetty** [comment]
How can I go about adding a new directive for the above. I have tried something as follows:-
```javascript
module.directive("focusHide", ["focusManager", "focusQuery", function (focusManager, focusQuery) {
        var hideElement = null;
        return {
            link: function (scope, element, attrs) {
                hideElement = focusQuery.getElementId(focusManager.activeElement);
                scope.$on("$destroy", function () {
                    var el = focusQuery.getElement(hideElement);
                    if (el != null) {
                        focusManager.focus(el);
                    }
                });
            }
        };
    }]);
```

<div class="toggleLastItem" focus-hide focus-autofocus focus-index="1" role="button" aria-label="Hide">Test</div>

On destroy the function doesn't get called. Am I missing something?

**Comment by KavyaShetty** [comment]
Any updates on this?

**Comment by KavyaShetty** [comment]
Any updates on this?

**Comment by roboncode** [comment]
Thank you for your submission. It will be added to the backlog and reviewed.

**Comment by roboncode** [comment]
I provided an update to your example. This is just one way to go about what you are trying to achieve. Hope this helps. http://plnkr.co/edit/RVgirPohdxFsMPeM9HGy?p=preview

**Comment by KavyaShetty** [comment]
In the updated example when I click on 'Hide Div' focus doesn't remain on 'Show Div' button.

**Comment by roboncode** [comment]
Try this out and see if this gives you the expected results...
http://plnkr.co/edit/RVgirPohdxFsMPeM9HGy?p=preview

**Comment by roboncode** [comment]
If this issue still remains, please reopen.
